name: real_estate_ani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  countup: ^0.1.4
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  page_transition: ^2.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
